version: '3.1'

services:
  web:
    ports:
      - ${PORT:-8080}:8000
    build:
      context: .
      args:
        DATABASE_URL: postgres://codeanon:codeanon@db/codeanon
        ENV: ${ENV:-dev}
    environment:
      SECRET_KEY: ${SECRET_KEY:?Django secret key}
      DJANGO_HOST: ${DJANGO_HOST:?Server public host address}
      SQL_HOST: db
      SQL_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: codeanon
      POSTGRES_PASSWORD: codeanon
      POSTGRES_DB: codeanon

volumes:
  db_data: {}
